#ifndef GBOT_H
#define GBOT_H

#define PIN_MOTOR_IZQ_1 8
#define PIN_MOTOR_IZQ_2 9
#define PIN_MOTOR_IZQ_PWM 10

#define PIN_MOTOR_DER_1 12
#define PIN_MOTOR_DER_2 13
#define PIN_MOTOR_DER_PWM 11

#define PIN_SENSOR_ULTRASONICO 4

#define PIN_SENSOR_LINEA_IZQ 5
#define PIN_SENSOR_LINEA_DER 6

#endif